const mongoose = require("mongoose");

const employeeExtraAllocationSchema = new mongoose.Schema(
	{
		empId: { type: String, ref: "Employee" },
		companyName: { type: String, ref: "Company" },
		chequesType: { type: Array, default: [] },
		additionalRegHoursWorked: { type: Number, default: 0 },
		additionalRegHoursWorked2: { type: Number, default: 0 },
		additionalPayoutRegHoursWorked: { type: Number, default: 0 },
		additionalManualRegHoursWorked: { type: Number, default: 0 },
		additionalSuperficialRegHoursWorked: { type: Number, default: 0 },

		additionalOvertimeHoursWorked: { type: Number, default: 0 },
		additionalPayoutOvertimeHoursWorked: { type: Number, default: 0 },
		additionalManualOvertimeHoursWorked: { type: Number, default: 0 },
		additionalSuperficialOvertimeHoursWorked: { type: Number, default: 0 },

		additionalDblOvertimeHoursWorked: { type: Number, default: 0 },
		additionalPayoutDblOvertimeHoursWorked: { type: Number, default: 0 },
		additionalManualDblOvertimeHoursWorked: { type: Number, default: 0 },
		additionalSuperficialDblOvertimeHoursWorked: { type: Number, default: 0 },

		additionalStatDayHoursWorked: { type: Number, default: 0 },
		additionalPayoutStatDayHoursWorked: { type: Number, default: 0 },
		additionalManualStatDayHoursWorked: { type: Number, default: 0 },
		additionalSuperficialStatDayHoursWorked: { type: Number, default: 0 },

		additionalStatHoursWorked: { type: Number, default: 0 },
		additionalPayoutStatHoursWorked: { type: Number, default: 0 },
		additionalManualStatHoursWorked: { type: Number, default: 0 },
		additionalSuperficialStatHoursWorked: { type: Number, default: 0 },

		additionalVacationHoursWorked: { type: Number, default: 0 },
		additionalPayoutVacationHoursWorked: { type: Number, default: 0 },
		additionalManualVacationHoursWorked: { type: Number, default: 0 },
		additionalSuperficialVacationHoursWorked: { type: Number, default: 0 },

		additionalBereavementHoursWorked: { type: Number, default: 0 },
		additionalPayoutBereavementHoursWorked: { type: Number, default: 0 },
		additionalManualBereavementHoursWorked: { type: Number, default: 0 },
		additionalSuperficialBereavementHoursWorked: { type: Number, default: 0 },

		additionalPersonalDayHoursWorked: { type: Number, default: 0 },
		additionalPayoutPersonalDayHoursWorked: { type: Number, default: 0 },
		additionalManualPersonalDayHoursWorked: { type: Number, default: 0 },
		additionalSuperficialPersonalDayHoursWorked: { type: Number, default: 0 },

		additionalSickHoursWorked: { type: Number, default: 0 },
		additionalPayoutSickHoursWorked: { type: Number, default: 0 },
		additionalManualSickHoursWorked: { type: Number, default: 0 },
		additionalSuperficialSickHoursWorked: { type: Number, default: 0 },

		payPeriodStartDate: Date,
		payPeriodEndDate: Date,
		payPeriodPayDate: Date,
		payPeriodProcessingDate: Date,
		payPeriodNum: String,

		pILBenefitPay: { type: Number, default: 0 },
		commission: { type: Number, default: 0 },
		retroactive: { type: Number, default: 0 },
		reimbursement: { type: Number, default: 0 },
		bonus: { type: Number, default: 0 },
		terminationPayout: { type: Number, default: 0 },
		vacationPayout: { type: Number, default: 0 },
		vacationBalAdjust: { type: Number, default: 0 },
		vacationAccrual: { type: Number, default: 0 },
		vacationUsed: { type: Number, default: 0 },
		federalTax: { type: Number, default: 0 },
		provTax: { type: Number, default: 0 },
		incomeTax: { type: Number, default: 0 },

		regPayAmt: { type: Number, default: 0 },
		regPayAmt2: { type: Number, default: 0 },
		OTPayAmt: { type: Number, default: 0 },
		dblOTPayAmt: { type: Number, default: 0 },
		statPayAmt: { type: Number, default: 0 },
		statWorkPayAmt: { type: Number, default: 0 },
		vacationPayAmt: { type: Number, default: 0 },
		bereavementPayAmt: { type: Number, default: 0 },
		personalDayPayAmt: { type: Number, default: 0 },
		sickPayAmt: { type: Number, default: 0 },

		commissionPayout: { type: Number, default: 0 },
		retroactivePayout: { type: Number, default: 0 },
		reimbursementPayout: { type: Number, default: 0 },
		bonusPayout: { type: Number, default: 0 },
		terminationPayoutPayout: { type: Number, default: 0 },
		vacationPayoutPayout: { type: Number, default: 0 },
		vacationBalAdjustPayout: { type: Number, default: 0 },
		vacationAccrualPayout: { type: Number, default: 0 },
		vacationUsedPayout: { type: Number, default: 0 },
		federalTaxPayout: { type: Number, default: 0 },
		provTaxPayout: { type: Number, default: 0 },
		incomeTaxPayout: { type: Number, default: 0 },

		regPayAmtPayout: { type: Number, default: 0 },
		OTPayAmtPayout: { type: Number, default: 0 },
		dblOTPayAmtPayout: { type: Number, default: 0 },
		statPayAmtPayout: { type: Number, default: 0 },
		statWorkPayAmtPayout: { type: Number, default: 0 },
		vacationPayAmtPayout: { type: Number, default: 0 },
		bereavementPayAmtPayout: { type: Number, default: 0 },
		personalPayAmtPayout: { type: Number, default: 0 },
		sickPayAmtPayout: { type: Number, default: 0 },

		commissionManual: { type: Number, default: 0 },
		retroactiveManual: { type: Number, default: 0 },
		reimbursementManual: { type: Number, default: 0 },
		bonusManual: { type: Number, default: 0 },
		terminationPayoutManual: { type: Number, default: 0 },
		vacationPayoutManual: { type: Number, default: 0 },
		vacationBalAdjustManual: { type: Number, default: 0 },
		vacationAccrualManual: { type: Number, default: 0 },
		vacationUsedManual: { type: Number, default: 0 },
		federalTaxManual: { type: Number, default: 0 },
		provTaxManual: { type: Number, default: 0 },
		incomeTaxManual: { type: Number, default: 0 },

		regPayAmtManual: { type: Number, default: 0 },
		OTPayAmtManual: { type: Number, default: 0 },
		dblOTPayAmtManual: { type: Number, default: 0 },
		statPayAmtManual: { type: Number, default: 0 },
		statWorkPayAmtManual: { type: Number, default: 0 },
		vacationPayAmtManual: { type: Number, default: 0 },
		bereavementPayAmtManual: { type: Number, default: 0 },
		personalPayAmtManual: { type: Number, default: 0 },
		sickPayAmtManual: { type: Number, default: 0 },

		commissionSuperficial: { type: Number, default: 0 },
		pILBenefitPaySuperficial: { type: Number, default: 0 },
		retroactiveSuperficial: { type: Number, default: 0 },
		reimbursementSuperficial: { type: Number, default: 0 },
		bonusSuperficial: { type: Number, default: 0 },
		terminationPayoutSuperficial: { type: Number, default: 0 },
		vacationPayoutSuperficial: { type: Number, default: 0 },
		vacationBalAdjustSuperficial: { type: Number, default: 0 },
		vacationAccrualSuperficial: { type: Number, default: 0 },
		vacationUsedSuperficial: { type: Number, default: 0 },
		federalTaxSuperficial: { type: Number, default: 0 },
		provTaxSuperficial: { type: Number, default: 0 },
		incomeTaxSuperficial: { type: Number, default: 0 },

		regPayAmtSuperficial: { type: Number, default: 0 },
		OTPayAmtSuperficial: { type: Number, default: 0 },
		dblOTPayAmtSuperficial: { type: Number, default: 0 },
		statPayAmtSuperficial: { type: Number, default: 0 },
		statWorkPayAmtSuperficial: { type: Number, default: 0 },
		vacationPayAmtSuperficial: { type: Number, default: 0 },
		bereavementPayAmtSuperficial: { type: Number, default: 0 },
		personalPayAmtSuperficial: { type: Number, default: 0 },
		sickPayAmtSuperficial: { type: Number, default: 0 },

		totalAmountAllocated: { type: Number, default: 0 },
		totalSuperficialAmountAllocated: { type: Number, default: 0 },
		totalManualAmountAllocated: { type: Number, default: 0 },
		totalPayoutAmountAllocated: { type: Number, default: 0 },

		totalHoursWorked: { type: Number, default: 0 },
		totalSuperficialHoursWorked: { type: Number, default: 0 },
		totalManualHoursWorked: { type: Number, default: 0 },
		totalPayoutHoursWorked: { type: Number, default: 0 },

		unionDuesSuperficial: { type: Number, default: 0 },
		EE_EHPSuperficial: { type: Number, default: 0 },
		EE_EPPSuperficial: { type: Number, default: 0 },
		EE_EISuperficial: { type: Number, default: 0 },
		EE_CPPSuperficial: { type: Number, default: 0 },

		ER_EHPSuperficial: { type: Number, default: 0 },
		ER_EPPSuperficial: { type: Number, default: 0 },
		ER_EISuperficial: { type: Number, default: 0 },
		ER_CPPSuperficial: { type: Number, default: 0 },
	},
	{ timestamps: { createdAt: "createdOn", updatedAt: "updatedOn" } },
);

const EmployeeExtraAllocation = mongoose.model(
	"EmployeeExtraAllocation",
	employeeExtraAllocationSchema,
);

module.exports = EmployeeExtraAllocation;
