const mongoose = require("mongoose");

const employeeProfileInfoSchema = new mongoose.Schema(
	{
		empId: { type: String, ref: "Employee" },
		companyName: { type: String, ref: "Company" },
		manager: { type: String, ref: "Employee" },
		firstName: String,
		middleName: String,
		lastName: String,
		gender: String,
		emergencyFirstName: String,
		emergencyLastName: String,
		birthDate: Date,
		SIN: String,
		SINIv: String,
		maritalStatus: String,
		citizenship: String,
		workPermitNo: String,
		workPermitExpiryNo: String,
		userEmail: String,
		personalEmail: String,
		personalPhoneNum: { type: String, ref: "Employee" },
		businessEmail: String,
		businessPhoneNum: String,
		emergencyPersonalEmail: String,
		emergencyPersonalPhoneNum: String,
		emergencyContactRelationship: String,
		streetAddress: String,
		streetAddressSuite: String,
		city: String,
		province: String,
		country: String,
		postalCode: String,
		password: String,
		isAffiliate: Boolean,
		contentToShare: String,
		marketingComms: Boolean,
		insta: String,
		linkedIn: String,
		tiktok: String,
		youtube: String,
		affiliateCode: { type: String, unique: true },
	},
	{ timestamps: { createdAt: "createdOn", updatedAt: "updatedOn" } },
);

const EmployeeProfileInfo = mongoose.model("EmployeeProfileInfo", employeeProfileInfoSchema);

module.exports = EmployeeProfileInfo;
