const mongoose = require("mongoose");

const employeeROESchema = new mongoose.Schema({
	empId: { type: String, ref: "Employee" },
	companyName: { type: String, ref: "Company" },
	serialNoAmended: String,
	payrollReferenceNumber: String,
	payPeriodType: String,
	firstName: String,
	middleName: String,
	lastName: String,
	SIN: String,
	SINIv: String,
	streetAddress: String,
	streetAddressSuite: String,
	city: String,
	province: String,
	country: String,
	postalCode: String,
	employmentStartDate: Date,
	employmentLeaveDate: Date,
	finalPayPeriodEndDate: Date,
	occupation: String,
	reasonCode: String,
	expectedRecallDate: String,
	recallDate: Date,
	contactExtNumber: String,
	contactName: String,
	contactTelNumber: String,
	issuerExtNumber: String,
	issuerName: String,
	issuerTelNumber: String,
	preferredCommunication: String,
	insurableHours: { type: Array, default: [] },
	insurableEarnings: { type: Array, default: [] },
	vacationPayCode: String,
	vacationPayStartDate: Date,
	vacationPayEndDate: Date,
	statHolidayPay: { type: Array, default: [] },
	otherMoney: { type: Array, default: [] },
	reviewComments: String,
	specialPayments: { type: Array, default: [] },
	createdOn: { type: Date, default: Date.now },
	updatedOn: { type: Date, default: Date.now },
	positions: { type: Array, default: [] },
});

const EmployeeROE = mongoose.model("EmployeeROE", employeeROESchema);

module.exports = EmployeeROE;
