export const SPECIAL_PAYMENT_OPTIONS = [
	{
		code: "PSL01",
		description: "Paid sick leave (EI Insurable)",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		periodRequired: false,
	},
	{
		code: "WLI01",
		description: "Wage loss indemnity (Not EI insurable)",
		startRequired: false,
		endRequired: false,
		amountRequired: false,
		periodRequired: false,
	},
	{
		code: "WLI02",
		description: "Wage loss indemnity (EI Insurable)",
		startRequired: false,
		endRequired: false,
		amountRequired: false,
		periodRequired: false,
	},
	{
		code: "MAT01",
		description: "Paid Maternity/Parental/Compassionate Care/Family Caregiver leave (EI Insurable)",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		periodRequired: false,
	},
];

export const OTHER_MONIES_OPTIONS = [
	{
		code: "B05",
		description: "Bonus (Holiday)",
		startRequired: true,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "B06",
		description: "Bonus (Production/Incentive)",
		startRequired: true,
		endRequired: true,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "B07",
		description: "Bonus (Event)",
		startRequired: true,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "B08",
		description: "Bonus (Staying/Contract complete/End of season)",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "B09",
		description: "Bonus (Separation or retirement)",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "B10",
		description: "Bonus (Closure)",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "B11",
		description: "Bonus (Other)",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "E00",
		description: "Severance Pay",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: false,
	},
	{
		code: "G00",
		description: "Gratuities",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "H00",
		description: "Honorariums",
		startRequired: true,
		endRequired: true,
		amountRequired: true,
		insurable: false,
	},
	{
		code: "I00",
		description: "Sick Leave Credits",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "J00",
		description: "Retroactive Pay Adjustment",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "O00",
		description: "Other",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "Q00",
		description: "Profit Sharing",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "R00",
		description: "Retiring Allowance / Retirement Leave Credits",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: false,
	},
	{
		code: "S00",
		description: "Settlement Pay",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "T00",
		description: "Payout of Banked Overtime",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
	{
		code: "U12",
		description: "SUB Maternity/Parental/Compassionate Care/Family Caregiver Benefits",
		startRequired: false,
		endRequired: false,
		amountRequired: false,
		insurable: false,
	},
	{
		code: "U13",
		description: "SUB Layoff",
		startRequired: false,
		endRequired: false,
		amountRequired: false,
		insurable: false,
	},
	{
		code: "U14",
		description: "SUB Illness",
		startRequired: false,
		endRequired: false,
		amountRequired: false,
		insurable: false,
	},
	{
		code: "U15",
		description: "SUB Training",
		startRequired: false,
		endRequired: false,
		amountRequired: false,
		insurable: false,
	},
	{
		code: "Y00",
		description: "Pay in Lieu of Notice",
		startRequired: false,
		endRequired: false,
		amountRequired: true,
		insurable: true,
	},
];

const PAY_FREQUENCY_CODE = [
	{ name: "Bi-weekly", code: "B" },
	{ name: "Monthly", code: "M" },
	{ name: "Monthly non-standard", code: "O" },
	{ name: "Semi-monthly", code: "S" },
	{ name: "Semi-monthly non-standard", code: "E" },
	{ name: "Thirteen Pay Periods per year", code: "H" },
	{ name: "Weekly", code: "W" },
];

export const REASON_CODE = [
	{
		name: "AOO - Shortage of Work / End of Contract or Season",
	},
	{
		name: "A01 - Employer bankruptcy or receivership",
	},
	{
		name: "B00 - Strike or Lockout",
	},
	{ name: "D00 - Illness or Injury" },
	{ name: "E00 - Quit" },
	{ name: "E02 - Quit / Follow spouse" },
	{ name: "E03 - Quit / Return to school" },
	{ name: "E04 - Quit / Health reasons" },
	{ name: "E05 - Quit / Voluntary retirement" },
	{ name: "E06 - Quit / Take another job" },
	{ name: "E09 - Quit / Employer relocation" },
	{ name: "E10 - Quit / Care for a dependant" },
	{ name: "E11 - Quit / To become self-employed" },
	{ name: "F00 - Maternity" },
	{ name: "G00 - Mandatory retirement" },
	{ name: "G07 - Retirement / Approved workforce reduction" },
	{ name: "H00 - Work Sharing" },
	{ name: "J00 - Apprentice Training" },
	{ name: "K00 - Other" },
	{ name: "K12 - Other / Change of payroll frequency" },
	{ name: "K13 - Other / Change of ownership" },
	{ name: "K14 - Other / Requested by Employment Insurance" },
	{ name: "K15 - Other / Canadian Forces - Queen's Regulations / Orders" },
	{ name: "K16 - Other / At the employee's request" },
	{ name: "K17 - Other /  Change of Service Provider" },
	{ name: "M00 - Dismissal or suspension" },
	{ name: "M08 - Dismissal / Terminated within probationary period" },
	{ name: "N00 - Leave" },
	{ name: "P00 - Parental Leave" },
	{ name: "Z00 - Compassionate care / Family caregiver" },
];

export const VACATION_PAY_CODE = [
	{
		name: "1 - Included with each pay",
	},
	{
		name: "2 - Paid because no longer working",
	},
	{
		name: "3 - Paid for a vacation leave period",
	},
	{
		name: "4 - Anniversary",
	},
];

export const RECALL_OPTIONS = [
	{
		name: "N - Not Returning",
	},
	{
		name: "U - Unknown",
	},
	{
		name: "Y - Return Date",
	},
];
